export enum HomeSelectors {
  receiveButton = 'Home/Receive Button',
  buyButton = 'Home/Buy Button',
  sendButton = 'Home/Send Button',
  withdrawButton = 'Home/Withdraw Button',
  swapButton = 'Home/Swap Button',
  assetsTab = 'Home/Assets Tab',
  delegationTab = 'Home/Delegation Tab',
  activityTab = 'Home/Activity Tab',
  infoTab = 'Home/Info Tab',
  NFTsTab = 'Home/NFTs Tab',
  publicAddressButton = 'Home/Public Address Button',
  fiatTezSwitchButton = 'Home/Fiat-Tez Switch Button',
  fiatTezSwitchText = 'Home/Fiat-Tez Switch Text',
  notificationIconButton = 'Home/Notification Icon Button',
  delegateButton = 'Home/Delegate Button',
  addressModeSwitchButton = 'Home/Address Mode Switch Button',
  accountNameText = 'Home/Account Name Text',
  emptyStateText = 'Home/Empty State Text',
  rwasTab = 'Home/RWAs Tab',
  historyTab = 'Home/History Tab'
}
